name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # actions/checkoutのために必要
      pull_requests: write # reviewdog/action-suggesterのために必要
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 21 # toolchainで指定したバージョンと同じものを使う
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessApply build --scan
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Gradle reports
          path: build/reports
      - uses: reviewdog/action-suggester@v1
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: spotless